### ISSUE TITLE
提示 GeneratedMessageV3 class not found

### ISSUE THREAD

**Issue by alonWang** [kaelzhang/java-fastjson-protobuf#2]
protobuf版本为2.6.1

```java
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at ai.ost.fastjson_protobuf.SerializeConfig.<init>(SerializeConfig.java:16)
	at ai.ost.fastjson_protobuf.FastJsonProtobufHttpMessageConverter.<init>(FastJsonProtobufHttpMessageConverter.java:21)
	at com.c2vl.kgamebox.webservice.interceptor.WebConfiguration.configureMessageConverters(WebConfiguration.java:46)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurerComposite.configureMessageConverters(WebMvcConfigurerComposite.java:136)
	at org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration.configureMessageConverters(DelegatingWebMvcConfiguration.java:117)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.getMessageConverters(WebMvcConfigurationSupport.java:715)
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.requestMappingHandlerAdapter(WebMvcConfigurationSupport.java:526)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration.requestMappingHandlerAdapter(WebMvcAutoConfiguration.java:372)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$59bebf.CGLIB$requestMappingHandlerAdapter$5(<generated>)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$59bebf$$FastClassBySpringCGLIB$$dfd7cc40.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$59bebf.requestMappingHandlerAdapter(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 19 more
```

**Comment by alonWang** [comment]
我这边版本太低,sorry

**Comment by kaelzhang** [comment]
嗯，目前没有支持 protobuf v2，`GeneratedMessageV3` 需要 3 及以上
